### ISSUE TITLE
"Mark Previous as Read" button not showing up

### ISSUE THREAD

**Issue by nousernameavailableanymore** [kalvn/freshrss-mark-previous-as-read#2] opened 2024-04-04 16:54 UTC
I copied the required files to the extensions folder and enabled the extension in FreshRSS webui.

However, there is no button showing up in the footer of an article.

Is this the correct place to look for the button?
![image](https://github.com/kalvn/freshrss-mark-previous-as-read/assets/45376324/4aa3fe65-0d83-4ce6-82e4-9472a16b9f6d)

FreshRSS version 1.23.1

**Comment by kalvn** [comment] 2024-04-11 21:07
It could be related to the theme, as I tried to find an appropriate way to inject the new link in the footer of each article, but it's clearly not bulletproof.

Considering page **Settings/Display**, could you please let me know which theme you use and what icons you enabled in the table?

**Comment by nousernameavailableanymore** [comment] 2024-04-12 16:02
These are the icons I have enabled:
![image](https://github.com/kalvn/freshrss-mark-previous-as-read/assets/45376324/4ca5d1b8-839e-4dfa-a4e7-7a7e16f77929)

I m using the Nord theme only replacing some colors via the CSS extension.

But even with the **default theme, without CSS adn all icons enabled** I do not get any "mark previous as read" button:
![image](https://github.com/kalvn/freshrss-mark-previous-as-read/assets/45376324/49d99a47-ff75-4608-bd66-7a34bc8de178)

**Comment by kalvn** [comment] 2024-04-18 18:43
Hmm that's weird, I used the exact same setup and for me it appears properly. The new button is added before the date of publication, so as long as date is shown, it should be there.

Are you sure the extension is enabled?

![image](https://github.com/kalvn/freshrss-mark-previous-as-read/assets/6149640/b0bfef01-301c-400a-9176-efae18fa4714)

**Comment by kalvn** [comment] 2024-04-18 18:48
If so, can you please:

1. Open your FreshRSS instance
2. Open developer tools (F12)
3. Go to console tab
4. Refresh the page (F5)
5. Send me a screenshot of the console

And also, can you go in the Network tab after refresh and ensure that you see something that contains `ext.php?f=xExtension-MarkPreviousAsRead%2Fstatic%2Fscript.js&t=js`

**Comment by arseru** [comment] 2024-05-12 11:40
I bumped into the same issue and I found why it's happening. The display setting "Website" needs to be set to "Icon and name" - any other value there fails to load the extension properly (I had it set to "None"):

![image](https://github.com/kalvn/freshrss-mark-previous-as-read/assets/63916092/5a8bef91-90f7-4c7b-baac-1bf5169a0833)

**Comment by nousernameavailableanymore** [comment] 2024-05-12 22:37
@arseru 
I can confirm thats the same thing for me.

However, even then the plugin does not work correctly.

When selecting a category (lets say "News", which contains more than one feed, lets say "CNN" and "BBC"), then only the items from the specific feed will be marked as read (for example only "CNN") instead of all above items from the whole category.

So the plugin basically only seems to work when choosing the correct setting in "Website" and reading single feeds instead of categories.

**Comment by arseru** [comment] 2024-05-13 08:49
@nousernameavailableanymore although I agree it would be nice that the extension could handle multiple feeds to mark them all as read, I don't think the developer intended for that to happen, as it explicitly asks you when clicking the button: [Are you sure to mark as read all entries from "yourFeedName" above?](https://github.com/kalvn/freshrss-mark-previous-as-read/blob/main/xExtension-MarkPreviousAsRead/static/script.js#L20).

Thanks for creating this extension @kalvn! :D

**Comment by kalvn** [comment] 2024-05-13 14:01
@arseru : Nice catch, I wasn't aware about this setting (I'm actually a fairly new user of FreshRSS :)). I suppose it changes the HTML of the link description bar and makes the script that adds the button ineffective. I'll use your input to investigate and try to find a solution that works in all 4 cases.

@nousernameavailableanymore : @arseru has it right, my initial goal was to be able to mark all articles of a single feed as read, no matter whether I'm reading them in the dedicated feed or in the global feed. I admit it might feel counter-intuitive, especially given that the built-in shortcut to mark all previous items as read doesn't work this way.

I'm actually planning to offer the choice as a parameter, I just didn't have the time to progress on that lately.

I'll keep you posted.

**Comment by kalvn** [comment] 2024-05-18 12:32
Fixed with https://github.com/kalvn/freshrss-mark-previous-as-read/commit/b31bcf09ba02b033d2723e54797c25faa4464e19

**Closed by kalvn** 2024-05-18 12:32 UTC

**Comment by kalvn** [comment] 2024-05-20 20:07
@nousernameavailableanymore the [v1.1.0](https://github.com/kalvn/freshrss-mark-previous-as-read/releases/tag/v1.1.0) adds configuration that allows to apply the mark-as-read action to all previous links, even if they belong to different feeds.

**Comment by nousernameavailableanymore** [comment] 2024-05-20 20:44
@kalvn 
Seems to work fine on first glance.
Just some remarks regarding the wording:

1. when marking items in a category as read, it still says: "Are you sure to mark as read all above entries from \<feed of the article\>". This is a bit confusing as it still says that only the entries from this specific feed will be marked as read. A better message would be "Are you sure to mark all articles from this category as read?"
Even stranger, the message is different, depending on wether in "Website" "Icon and Name" is selected or "Icon only" (see below).
2. The configuration menu says: "Mark all above entries as read, not only those belonging to the same feed.". This makes it sound as if ALL entries will be marked as read, not just those in the same category. Maybe a better description would be: "
Mark all above entries in the same category as read, not only those belonging to the same feed."



Icon and name
![image](https://github.com/kalvn/freshrss-mark-previous-as-read/assets/45376324/df0c5d3e-1728-4dfb-9ae6-4f78dd8bbc9b)

Icon only 
![image](https://github.com/kalvn/freshrss-mark-previous-as-read/assets/45376324/dbb914d1-6707-499e-9bdf-aeed935bd409)

**Comment by kalvn** [comment] 2024-05-20 20:56
I indeed forgot to adapt the wording to reflect the configuration, I'll do that.

About the message that changes depending on whether you display icon + title or icon only, it is because when feed title is missing, I have no way to know which feed the entry belongs to. So I opted for a more generic message.

Thanks for the feedback on wording, I have to admit it is tricky to come up with. It is not always clear to me how to name things in FreshRSS. The difference between feed, category, entry, etc. is not always obvious. I'll find something better.

**Comment by nousernameavailableanymore** [comment] 2024-05-21 04:57
@kalvn 
Why not stick to the official wording in FreshRSS?

There are feeds, which can be organized in categories. Are there any more entities (maybe I m missing something)?

![image](https://github.com/kalvn/freshrss-mark-previous-as-read/assets/45376324/afc5e515-9d1c-4499-8552-0f0a20902fd6)

**Comment by kalvn** [comment] 2024-05-25 13:04
Wording should now be more accurate in [v1.1.1](https://github.com/kalvn/freshrss-mark-previous-as-read/releases/tag/v1.1.1).

**Comment by arseru** [comment] 2024-07-01 11:40
I can confirm it works for me in v1.1.1 - from a category view, it now marks all previous items from multiple feeds as Read. Thanks a lot @kalvn !
